version: '3'

services:
  ah-web:
    container_name: ah-web
    image: ah-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
      - '/home/ubuntu/Website2022/test-folder/server/frontend/build:/app/build'
    ports:
      - '3001:3001'
    command: 'npm run build'
